// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://chofmiwkypedtwhsikmh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNob2ZtaXdreXBlZHR3aHNpa21oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzMTg3MzYsImV4cCI6MjA3MTg5NDczNn0.vk5pixAQ3mOnp5N3_l3tKr92rE6pQinKQeEspVldaDo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});